# Generated by Django 4.0.4 on 2022-04-19 20:49

import django.core.validators
from django.db import migrations, models
import puzzle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontal_rows', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20), puzzle.models.validate_odd])),
                ('vertical_rows', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Horizontal9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(help_text='1', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^1')], verbose_name='A')),
                ('b', models.TextField(help_text='2', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^2')], verbose_name='B')),
                ('c', models.TextField(help_text='3', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^3')], verbose_name='C')),
                ('d', models.TextField(help_text='4', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^4')], verbose_name='D')),
                ('e', models.TextField(help_text='5', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^5')], verbose_name='E')),
                ('f', models.TextField(help_text='6', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^6')], verbose_name='F')),
                ('g', models.TextField(help_text='7', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^7')], verbose_name='G')),
                ('H', models.TextField(help_text='8', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^8')], verbose_name='8')),
                ('i', models.TextField(help_text='9', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^9')], verbose_name='I')),
                ('J', models.TextField(help_text='10', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^10')], verbose_name='10')),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontal_rows', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('vertical_rows', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
        ),
    ]
